name: AsgardCommand
description: 阿萨神谕 (深度条件命令替换插件)
main: me.asgard.asgardcommand.AsgardCommand
version: ${project.version}

softdepend: [SacredItem]

author: hotic

commands:
  ac:
    description: 神谕主命令
    aliases: [asgardcommand]